### ISSUE TITLE
Specific hue hex colors not working

### ISSUE THREAD

**Issue by HannesDeMets** [davidmerfield/randomColor#123] opened 2019-04-29 13:02 UTC
When i pass the hexadecimal `#fec300` value to the hue key, i get the following error:

`var randomColor = randomColor({ hue: '#fec300' });`

<img width="450" alt="Screenshot 2019-04-29 at 14 56 20" src="https://user-images.githubusercontent.com/35343856/56897488-f764f600-6a8e-11e9-93e5-eb9ef5e92017.png">

I had the same result when testing with: `#fec200`, `#fec400`, `#fec500` and `#fec600`

**Comment by davidmerfield** [comment] 2019-04-29 14:53
[Cannot reproduce](https://jsfiddle.net/d6af3qwn/) with the latest version of the library. Please send me a link to a page which demonstrates the issue

**Comment by maximtmartin** [comment] 2019-04-30 08:18
This problem happens when you set count option to 1;

`randomColor({hue: '#fec300', count: 1})`

**Comment by KyleFoleyImajion** [comment] 2019-05-14 17:15
Having the exact same issue with the color #FF00DB

**Comment by davidmerfield** [comment] 2019-05-14 18:14
Understood, will fix

**Comment by SethPaulM** [comment] 2019-06-12 12:48
Is there any update on the status of this fix?

**Comment by davidmerfield** [comment] 2019-06-13 09:06
@SethPaulM No, but if you subscribe to this issue you will be notified when it's closed

**Comment by msd7manoj** [comment] 2020-07-05 06:42
Is this bug fixed? Facing the same issue

**Comment by davidmerfield** [comment] 2020-07-14 19:11
Should now be fixed in 0.6.1, available from npm right now!

**Closed by davidmerfield** 2020-07-14 19:11 UTC
Labels: bug
