### ISSUE TITLE
Possible to exclude colours?

### ISSUE THREAD

**Issue by Koshux** [davidmerfield/randomColor#82] opened 2017-03-03 16:05 UTC
First of all thank you for this library!  Secondly, I encountered a situation where I would like to generate colours sequentially however once a colour has been generated, I would like the next generated colours to exclude the already existing ones (given an array of some sort).  Would you think this be possible?

I just realised that issue #58 is practically the same query.

**Comment by card100** [comment] 2017-03-23 17:42
Double https://github.com/davidmerfield/randomColor/issues/58

**Comment by davidmerfield** [comment] 2017-03-28 15:14
Going to close this since it is a duplicate of #58, thanks @Koshux and @card100.

**Closed by davidmerfield** 2017-03-28 15:14 UTC
