### ISSUE TITLE
[feat. request] unique colors

### ISSUE THREAD

**Issue by undavide** [davidmerfield/randomColor#101] opened 2018-01-31 16:10 UTC
Hi,
I've noticed that, when generating large number of colors, they may repeat – it would be nice to have a `"unique: true"` option.
Thanks! (yes, I have to generate an awful amount of colors... :-) )

**Comment by davidmerfield** [comment] 2018-01-31 16:43
Hi Davide! Thanks for giving the script a go. 

I consider this a duplicate of a previous issue, #50, Maximizing color difference. Am going to close this issue for now. Let me know if you have any questions.

**Closed by davidmerfield** 2018-01-31 16:43 UTC
